version: '3'

services:
  next-app-dev:
    container_name: next-app-dev
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
