version: '3'

services:
  next-blog-app-dev:
    container_name: next-blog-app-dev
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./_posts:/app/_posts
      - ./components:/app/components
      - ./interfaces:/app/interfaces
      - ./lib:/app/lib
      - ./pages:/app/pages
      - ./public:/app/public
      - ./src:/app/src
    ports:
      - 3001:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
